#!/usr/bin/env bash
# Reproducible release: frontend -> sidecar -> hotpath -> Tauri bundle -> dist/
#
# Modes:
#   (default)       FULL release. Requires the Tauri CLI + a build host that
#                   can produce at least one native installer. Fails hard
#                   otherwise — a "release" with no installers is a bug.
#   --source-only   SOURCE-only build. Stamps versions and builds frontend +
#                   Rust crates so the tree is buildable, but skips sidecar
#                   bundling and Tauri bundling. Used inside CI matrices where
#                   per-OS installers are produced separately and merged later,
#                   or to validate the source tree on a host that can't bundle.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

MODE="full"
for arg in "$@"; do
  case "$arg" in
    --source-only) MODE="source-only" ;;
    *) echo "!! Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

VERSION="$(cat VERSION | tr -d '[:space:]')"
echo "==> Zoc AI release ${VERSION} (mode: ${MODE})"

# 0. Stamp version everywhere.
echo "==> Stamping version manifests"
python3 scripts/stamp_version.py

# 1. Frontend.
echo "==> Building frontend"
pnpm install --frozen-lockfile || pnpm install
pnpm --filter @llama-studio/frontend build

# 2. Rust hot-path crate -> bundled into Tauri as a second externalBin.
echo "==> Building hotpath crate (release)"
cargo build --release -p llama-studio-hotpath

echo "==> Staging hotpath binary for Tauri externalBin"
TRIPLE="${LLAMA_STUDIO_TARGET_TRIPLE:-$(rustc -vV | awk '/^host:/ {print $2}')}"
HP_SUFFIX=""
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) HP_SUFFIX=".exe" ;;
esac
HP_SRC="target/release/llama-studio-hotpath${HP_SUFFIX}"
HP_DST="apps/desktop/binaries/llama-studio-hotpath-${TRIPLE}${HP_SUFFIX}"
if [ ! -f "$HP_SRC" ]; then
  echo "!! Expected hotpath binary at $HP_SRC but it is missing." >&2
  exit 1
fi
mkdir -p apps/desktop/binaries
cp -f "$HP_SRC" "$HP_DST"
chmod +x "$HP_DST" || true
echo "==> Hotpath staged at $HP_DST"

if [ "$MODE" = "source-only" ]; then
  echo "==> --source-only: skipping sidecar bundle, Tauri bundle, and artifact collection."
  echo "==> Source tree is stamped and frontend/hotpath are built."
  exit 0
fi

# 3. FastAPI sidecar -> single-file executable.
echo "==> Bundling agent sidecar"
if ! uv run python3 scripts/bundle_sidecar.py; then
  echo "!! Sidecar bundling failed; cannot continue with Tauri build." >&2
  exit 1
fi

# 4. Tauri bundle (per-OS installers). FAIL HARD if the CLI is missing or
# the build does not produce any installer artifacts — a release without
# installers is a bug, not a soft warning.
echo "==> Building Tauri bundles"
if ! (command -v cargo-tauri >/dev/null 2>&1 \
      || pnpm --filter @llama-studio/desktop exec tauri --version >/dev/null 2>&1); then
  cat >&2 <<EOF
!! Tauri CLI is not available in this environment.
!! A full release REQUIRES the Tauri CLI and a supported build host.
!! Install with: pnpm --filter @llama-studio/desktop add -D @tauri-apps/cli
!! Or rerun with: bash scripts/release.sh --source-only
EOF
  exit 1
fi
# We just built the frontend, hotpath, and sidecar above, so tell Tauri's
# beforeBuildCommand (scripts/prepare_tauri_build.sh) to skip — otherwise it
# would redo the slow sidecar bundle a second time.
LLAMA_STUDIO_SKIP_PREPARE=1 pnpm --filter @llama-studio/desktop build

# 5. Collect artifacts into dist/.
echo "==> Preparing dist/installers/"
rm -rf dist/installers
mkdir -p dist/installers
# Tauri v2 emits bundles under target/release/bundle/<format>/...
# Linux package formats produced by this release: .deb, .rpm, and .tar.gz
# (the .tar.gz is generated by the post-build step below).
if [ -d target/release/bundle ]; then
  echo "==> Collecting Tauri bundles into dist/installers/"
  # File-shaped installers.
  while IFS= read -r -d '' f; do
    cp -a "$f" dist/installers/
  done < <(find target/release/bundle -type f \
    \( -name '*.deb' -o -name '*.rpm' \
       -o -name '*.msi' -o -name '*.exe' -o -name '*.dmg' \) -print0)
  # macOS .app is a directory; copy the whole bundle.
  while IFS= read -r -d '' d; do
    cp -aR "$d" dist/installers/
  done < <(find target/release/bundle -type d -name '*.app' -prune -print0)
fi
# hotpath CLI binary
if [ -f target/release/llama-studio-hotpath ]; then
  cp target/release/llama-studio-hotpath dist/ || true
elif [ -f target/release/llama-studio-hotpath.exe ]; then
  cp target/release/llama-studio-hotpath.exe dist/ || true
fi

# 5b. Linux: build a portable .tar.gz from the release binaries. Tauri v2 has
# no built-in tar.gz target, so we pack the desktop binary + hotpath + the
# bundled sidecar runtime into a single archive that runs without a package
# manager.
if [ "$(uname -s)" = "Linux" ] && [ -f target/release/llama-studio ]; then
  TARBALL="dist/installers/llama-studio-${VERSION}-linux-x86_64.tar.gz"
  STAGE="$(mktemp -d)"
  PKG_DIR="${STAGE}/llama-studio-${VERSION}"
  mkdir -p "${PKG_DIR}/bin"
  cp -a target/release/llama-studio "${PKG_DIR}/bin/"
  if [ -f target/release/llama-studio-hotpath ]; then
    cp -a target/release/llama-studio-hotpath "${PKG_DIR}/bin/"
  fi
  SIDECAR_SRC=""
  if [ -f target/release/llama-studio-agent${HP_SUFFIX} ]; then
    SIDECAR_SRC="target/release/llama-studio-agent${HP_SUFFIX}"
  elif [ -f "apps/desktop/binaries/llama-studio-agent-${TRIPLE}${HP_SUFFIX}" ]; then
    SIDECAR_SRC="apps/desktop/binaries/llama-studio-agent-${TRIPLE}${HP_SUFFIX}"
  fi
  if [ -z "$SIDECAR_SRC" ]; then
    echo "!! Expected sidecar binary at target/release/llama-studio-agent${HP_SUFFIX} or apps/desktop/binaries/llama-studio-agent-${TRIPLE}${HP_SUFFIX}." >&2
    exit 1
  fi
  cp -a "$SIDECAR_SRC" "${PKG_DIR}/bin/llama-studio-agent${HP_SUFFIX}"
  chmod +x "${PKG_DIR}/bin/llama-studio" \
    "${PKG_DIR}/bin/llama-studio-agent${HP_SUFFIX}" \
    "${PKG_DIR}/bin/llama-studio-hotpath${HP_SUFFIX}" 2>/dev/null || true
  # Keep the PyInstaller sidecar payload directory for diagnostics and for
  # parity with the Tauri externalBin staging layout.
  if [ -d apps/desktop/binaries ]; then
    mkdir -p "${PKG_DIR}/binaries"
    cp -a apps/desktop/binaries/. "${PKG_DIR}/binaries/" 2>/dev/null || true
  fi
  for doc in README.md VERSION LICENSE CHANGELOG.md; do
    [ -f "$doc" ] && cp -a "$doc" "${PKG_DIR}/" || true
  done
  tar -C "${STAGE}" -czf "${TARBALL}" "llama-studio-${VERSION}"
  rm -rf "${STAGE}"
  echo "==> Linux .tar.gz: ${TARBALL}"
fi

shopt -s nullglob
installers=(dist/installers/*)
shopt -u nullglob
if [ "${#installers[@]}" -eq 0 ]; then
  echo "!! Tauri build completed but produced NO installers in dist/installers/." >&2
  echo "!! Check target/release/bundle/ and the bundle target list in tauri.conf.json." >&2
  exit 1
fi

echo "==> Release artifacts written to dist/"
ls -la dist/ dist/installers/ || true
